# Generated by Django 4.1.3 on 2022-12-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=225)),
                ('total', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.register_tb')),
            ],
        ),
    ]
